import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingTop: 20,
    paddingHorizontal: 16,
    // backgroundColor: "yellow",
  },
  title: {
    fontSize: 25,
    fontFamily: "Gabarito-Bold",
    margin: 0,
    color: "#262626",
  },
  subtitle: {
    fontSize: 24,
    fontFamily: "Gabarito-Bold",
    marginBottom: 10,
  },
  header: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 15,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  btnContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 32,
    marginBottom: 10,
    gap: 32,
  },
  uploadBtn: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#262626",
    paddingVertical: 20,
    paddingHorizontal: 30,
  },
  btnText: {
    fontFamily: "Nunito-Regular",
    fontSize: 12,
  },
  dividerText: {
    fontFamily: "Gabarito-Bold",
    fontSize: 32,
    textAlign: "center",
    marginVertical: 10,
    color: "#262626",
  },
  textarea: {
    fontFamily: "Nunito-Regular",
    fontSize: 16,
    height: 300,
    borderWidth: 2,
    borderRadius: 8,
    padding: 16,
  },
  btnContent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 100,
    backgroundColor: "#7000FF",
    paddingVertical: 16,
  },

  optionsContainer: {
    display: "flex",
    flexDirection: "column",
    marginVertical: 20,
    gap: 20,
  },
  optionContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 16,
    padding: 16,
    borderWidth: 2,
    borderRadius: 16,
    borderColor: "#262626",
  },
  optionText: {
    fontFamily: "Gabarito-Bold",
    fontSize: 19,
    color: "#262626",
  },
  btnTextOption: {
    fontFamily: "Gabarito-Bold",
    color: "white",
    fontSize: 22,
  },
  selectedOption: {
    backgroundColor: "#7000FF",
    borderWidth: 2,
    borderColor: "#7000FF",
  },
  selectedOptionText: {
    color: "white",
  },
  btnContainerSelector: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderTopColor: "#CDCDCD",
    borderTopWidth: 2,
    // backgroundColor: "#FFF",
    position: "absolute",
    bottom: 0,
    left: -16,
    right: -16,
    zIndex: 100,
  },
  btnDisabled: {
    backgroundColor: "#F5F5F5",
    borderColor: "#CDCDCD",
    borderWidth: 2,
  },
  textDisabled: {
    color: "#CDCDCD",
  },
});
