import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    margin: 0,
  },
  header: {
    backgroundColor: "#7000FF",
    padding: 25,
    paddingLeft: 16,
    paddingBottom: 10,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  headerTitle: {
    fontSize: 26,
    fontFamily: "Gabarito-Bold",
    color: "#FFF",
    textAlign: "center",
  },
  headerSubtitle: {
    fontSize: 14,
    fontFamily: "Nunito-Regular",
    color: "#FFF",
    textAlign: "center",
    marginBottom: 10,
  },
  scoreBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 15,
  },
  score: {
    fontFamily: "Gabarito-Bold",
    fontSize: 62,
    color: "#FFF",
  },
  totalAnsBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 100,
    backgroundColor: "#FEE702",
    marginBottom: 10,
  },
  totalAns: {
    fontFamily: "Nunito-Bold",
    fontSize: 16,
    color: "#000",
  },
  contentBox: {
    padding: 24,
  },
  reviewAnsBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 16,
    marginBottom: 24,
  },
  reviewTitle: {
    fontSize: 20,
    fontFamily: "Gabarito-Bold",
    color: "#7000FF",
    marginBottom: 7,
  },
  answersBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    borderRadius: 10,
    gap: 8,
    height: 65,
    width: 40,
  },
  answers: {
    fontSize: 16,
    fontFamily: "Nunito-Bold",
    color: "#FFF",
  },
  timeConsumed: {
    fontFamily: "Nunito-Bold",
    fontSize: 16,
    color: "#7000FF",
  },
  answerCard: {
    borderColor: "black",
    borderWidth: 2,
    borderRadius: 10,
    padding: 16,
    paddingTop: 32,
    marginBottom: 24,
  },
  answerTitle: {
    fontFamily: "Nunito-Bold",
    fontSize: 16,
    color: "#262626",
    marginBottom: 10,
  },
  answerDetail: {
    fontFamily: "Nunito-SemiBold",
    fontSize: 16,
    color: "#262626",
    marginBottom: 5,
  },
  iconBox: {
    position: "absolute",
    right: 10,
    top: -14,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
    borderRadius: 8,
    borderWidth: 2,
    width: 40,
    height: 40,
  },
  askAI: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF4c4c",
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderRadius: 10,
    alignSelf: "flex-end",
  },
  askAIText: {
    fontFamily: "Nunito-Bold",
    fontSize: 16,
    color: "#FFF",
  },
  btnWrapper: {
    display: "flex",
    position: "absolute",
    left: 0,
    right: 0,
    padding: 16,
    paddingBottom: 30,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 32,
    gap: 10,
    backgroundColor: "#FFF",
    borderTopWidth: 2,
    borderTopColor: "#CDCDCD",
  },
  btns: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: "#7000FF",
  },
  btnsText: {
    fontFamily: "Gabarito-Bold",
    fontSize: 18,
    color: "#7000FF",
  },
});
